version: '2.1'
networks:
  default:
    ipam:
      driver: default
services:

  jackett:
    image: linuxserver/jackett
    depends_on:
      - vpn
    restart: always
    network_mode: "service:vpn"
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/Moscow
    volumes:
      - /volume1/docker/compose/jackett:/config
      - /volume1/Media/downloads/jackett:/downloads

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
#    environment:
#      - PUID=1026
#      - PGID=100
    volumes:
      - ./sonarr:/config
      - /volume1/Media/Tvshows:/serials
      - /volume1/Media/downloads:/downloads
    ports:
      - 8989:8989
    restart: always

  radarr:
    image: linuxserver/radarr
    container_name: radarr
#    environment:
#      - PUID=1026
#      - PGID=100
    volumes:
      - ./radarr:/config
      - /volume1/Media/Movies:/movies
      - /volume1/Media/downloads:/downloads
    ports:
      - 7878:7878
    restart: always

  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    dns:
     - 8.8.4.4
     - 8.8.8.8
    environment:
      TZ: 'Europe/Moscow'
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - /volume1/docker/compose/vpn:/vpn
    ports:
     - "9117:9117/tcp"

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - ./transmission:/config
      - /volume1/Media/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped